# Site wide configuration

title: Paul Blischak
description: "Research website"
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url: http://pblischak.github.io

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Paul Blischak
  email: blischak.4@osu.edu
  twitter: PaulBlischak
  github: pblischak 
  bio: "PhD student in Dept. of EEOB at Ohio State"
  avatar: #bio-photo.jpg # 160x160 px image for author byline
disqus-shortname: 


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
